import { PGlite } from '@electric-sql/pglite';
import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';
const db = new PGlite();
const schema = JSON.parse(readFileSync(new URL('../../docs/schema-before-mvp.json', import.meta.url))).tables;
await db.exec(`create role anon; create role authenticated; create schema auth;
 create table auth.users(id uuid primary key);
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 grant usage on schema public,auth to authenticated,anon; grant execute on function auth.uid() to authenticated,anon;`);
const quote = (v) => '"'+v.replaceAll('"','""')+'"';
for (const table of schema) {
 const columns=table.columns.map(c=>`${quote(c.name)} ${c.data_type === 'character varying' ? 'varchar' : c.data_type} ${c.options.includes('identity') ? 'generated by default as identity' : c.default_value ? 'default '+c.default_value : ''} ${c.options.includes('nullable') ? '' : 'not null'}`);
 await db.exec(`create table ${table.name.split('.').map(quote).join('.')} (${columns.join(',')}, primary key (${table.primary_keys.map(quote).join(',')}));`);
}
const seen = new Set();
for (const table of schema) for (const fk of table.foreign_key_constraints ?? []) {
 if (seen.has(fk.name)) continue; seen.add(fk.name);
 await db.exec(`alter table ${fk.source_table.split('.').map(quote).join('.')} add constraint ${quote(fk.name)} foreign key(${fk.source_columns.map(quote)}) references ${fk.target_table.split('.').map(quote).join('.')}(${fk.target_columns.map(quote)});`);
}
await db.exec("insert into public.product(id,name,price,stock) values(101,'Legacy',10,null); insert into public.favorite(items_id) values(null);");
await db.exec(readFileSync(new URL('../../supabase/migrations/20260928115505_wasteless_commerce.sql',import.meta.url),'utf8'));
const A='11111111-1111-4111-8111-111111111111', B='22222222-2222-4222-8222-222222222222';
await db.query('insert into auth.users values($1),($2)',[A,B]);
await db.exec("insert into public.product(name,price,stock) values('A',3.40,10),('B',2.80,20),('C',1.20,0)");
assert.equal((await db.query('select stock from public.product where id=101')).rows[0].stock,null);
assert.equal((await db.query('select count(*)::int as n from public.favorite where user_id is null')).rows[0].n,1);
let checks=2;
const check=(value, expected)=>{assert.deepEqual(value,expected);checks++;};
async function asUser(u, sql, params=[]) {
 return db.transaction(async tx=>{
  await tx.exec('set local role authenticated');
  await tx.query("select set_config('request.jwt.claim.sub',$1,true)",[u]);
  return (await tx.query(sql,params)).rows;
 });
}
async function denied(u,sql,params=[]) {await assert.rejects(asUser(u,sql,params));checks++;}
check((await asUser(A,'select id from product')).length,3);
await asUser(A,"select wasteless_cart('add',2,null,2)");
check((await asUser(A,'select product_id,quantity from cart_items'))[0],{product_id:2,quantity:2});
check((await asUser(B,'select * from cart_items')).length,0);
await asUser(B,"select wasteless_cart('add',1,null,1)");
const item=(await asUser(A,'select id from cart_items'))[0].id;
await denied(B,"select wasteless_cart('set',null,$1,3)",[item]);
await denied(B,"select wasteless_cart('remove',null,$1,null)",[item]);
await denied(A,'update cart set user_id=$1',[B]);
await asUser(A,"select wasteless_cart('set',null,$1,3)",[item]);
check((await asUser(A,'select quantity from cart_items'))[0].quantity,3);
await asUser(A,"select wasteless_cart('set',null,$1,0)",[item]);
check((await asUser(A,'select * from cart_items')).length,0);
await denied(A,"select wasteless_cart('add',3,null,1)");
await denied(A,"select wasteless_cart('add',1,null,-1)");
await asUser(A,'select wasteless_favorite(1,true)');
await asUser(A,'select wasteless_favorite(2,true)');
await asUser(A,'select wasteless_favorite(2,true)');
check((await asUser(A,'select items_id from favorite order by items_id')).map(x=>x.items_id),[1,2]);
check((await asUser(B,'select * from favorite')).length,0);
await asUser(B,'select wasteless_favorite(1,false)');
check((await asUser(A,'select * from favorite')).length,2);
await asUser(A,'select wasteless_favorite(1,false)');
check((await asUser(A,'select items_id from favorite')).map(x=>x.items_id),[2]);
await asUser(A,"select wasteless_cart('add',1,null,2)");
await asUser(A,"select wasteless_cart('add',2,null,1)");
const key='33333333-3333-4333-8333-333333333333';
const oid=(await asUser(A,'select wasteless_checkout($1) as id',[key]))[0].id;
check((await asUser(A,'select total_price::text as total from "order"'))[0].total,'9.60');
check((await asUser(A,'select * from order_items')).length,2);
check((await asUser(B,'select * from "order"')).length,0);
check((await asUser(B,'select * from order_items')).length,0);
check((await asUser(A,'select * from cart_items')).length,0);
check((await asUser(A,'select wasteless_checkout($1) as id',[key]))[0].id,oid);
check((await asUser(A,'select * from "order"')).length,1);
await denied(A,'insert into "order"(user_id,total_price) values($1,0)',[A]);
await db.exec('update product set price=99 where id=1');
check((await asUser(A,'select unit_price::text as price from order_items where product_id=1'))[0].price,'3.40');
await db.exec('update product set stock=0 where id=1');
await denied(B,'select wasteless_checkout($1)',[key]);
check((await asUser(B,'select * from "order"')).length,0);
check((await asUser(B,'select * from cart_items')).length,1);
await db.transaction(async tx=>{
 await tx.exec('set local role anon');
 await assert.rejects(tx.query('select * from cart'));checks++;
});
await db.exec('create schema tebelenoi; create table tebelenoi.cart(id bigint); grant select on tebelenoi.cart to anon,authenticated;');
await db.exec(readFileSync(new URL('../../supabase/migrations/20260928120848_wasteless_legacy_access.sql',import.meta.url),'utf8'));
check((await db.query("select relrowsecurity from pg_class where oid='tebelenoi.cart'::regclass")).rows[0].relrowsecurity,true);
check((await db.query("select has_table_privilege('anon','tebelenoi.cart','select') as permitted")).rows[0].permitted,false);
console.log(`${checks} database checks passed: real SQL migration, RLS, ownership, stock, price snapshots, rollback and idempotency.`);
await db.close();
