import { PGlite } from '@electric-sql/pglite';
import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';
const db = new PGlite();
const schema = JSON.parse(readFileSync(new URL('../../docs/schema-before-mvp.json', import.meta.url))).tables;
await db.exec(`create role anon; create role authenticated; create schema auth;
 create table auth.users(id uuid primary key);
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 grant usage on schema public,auth to authenticated,anon; grant execute on function auth.uid() to authenticated,anon;`);
const quote = (v) => '"'+v.replaceAll('"','""')+'"';
for (const table of schema) {
 const columns=table.columns.map(c=>`${quote(c.name)} ${c.data_type === 'character varying' ? 'varchar' : c.data_type} ${c.options.includes('identity') ? 'generated by default as identity' : c.default_value ? 'default '+c.default_value : ''} ${c.options.includes('nullable') ? '' : 'not null'}`);
 await db.exec(`create table ${table.name.split('.').map(quote).join('.')} (${columns.join(',')}, primary key (${table.primary_keys.map(quote).join(',')}));`);
}
const seen = new Set();
for (const table of schema) for (const fk of table.foreign_key_constraints ?? []) {
 if (seen.has(fk.name)) continue; seen.add(fk.name);
 await db.exec(`alter table ${fk.source_table.split('.').map(quote).join('.')} add constraint ${quote(fk.name)} foreign key(${fk.source_columns.map(quote)}) references ${fk.target_table.split('.').map(quote).join('.')}(${fk.target_columns.map(quote)});`);
}
await db.exec("insert into public.product(id,name,price,stock) values(101,'Legacy',10,null); insert into public.favorite(items_id) values(null);");
await db.exec(readFileSync(new URL('../../supabase/migrations/20260928173209_wasteless_commerce.sql',import.meta.url),'utf8'));
const A='11111111-1111-4111-8111-111111111111', B='22222222-2222-4222-8222-222222222222';
await db.query('insert into auth.users values($1),($2)',[A,B]);
await db.exec("insert into public.product(name,price,stock) values('A',3.40,10),('B',2.80,20),('C',1.20,0)");
assert.equal((await db.query('select stock from public.product where id=101')).rows[0].stock,null);
assert.equal((await db.query('select count(*)::int as n from public.favorite where user_id is null')).rows[0].n,1);
let checks=2;
const check=(value, expected)=>{assert.deepEqual(value,expected);checks++;};
async function asUser(u, sql, params=[]) {
 return db.transaction(async tx=>{
  await tx.exec('set local role authenticated');
  await tx.query("select set_config('request.jwt.claim.sub',$1,true)",[u]);
  return (await tx.query(sql,params)).rows;
 });
}
async function denied(u,sql,params=[]) {await assert.rejects(asUser(u,sql,params));checks++;}
check((await asUser(A,'select id from product')).length,3);
await asUser(A,"select wasteless_cart('add',2,null,2)");
check((await asUser(A,'select product_id,quantity from cart_items'))[0],{product_id:2,quantity:2});
check((await asUser(B,'select * from cart_items')).length,0);
await asUser(B,"select wasteless_cart('add',1,null,1)");
const item=(await asUser(A,'select id from cart_items'))[0].id;
await denied(B,"select wasteless_cart('set',null,$1,3)",[item]);
await denied(B,"select wasteless_cart('remove',null,$1,null)",[item]);
await denied(A,'update cart set user_id=$1',[B]);
await asUser(A,"select wasteless_cart('set',null,$1,3)",[item]);
check((await asUser(A,'select quantity from cart_items'))[0].quantity,3);
await asUser(A,"select wasteless_cart('set',null,$1,0)",[item]);
check((await asUser(A,'select * from cart_items')).length,0);
await denied(A,"select wasteless_cart('add',3,null,1)");
await denied(A,"select wasteless_cart('add',1,null,-1)");
await asUser(A,'select wasteless_favorite(1,true)');
await asUser(A,'select wasteless_favorite(2,true)');
await asUser(A,'select wasteless_favorite(2,true)');
check((await asUser(A,'select items_id from favorite order by items_id')).map(x=>x.items_id),[1,2]);
check((await asUser(B,'select * from favorite')).length,0);
await asUser(B,'select wasteless_favorite(1,false)');
check((await asUser(A,'select * from favorite')).length,2);
await asUser(A,'select wasteless_favorite(1,false)');
check((await asUser(A,'select items_id from favorite')).map(x=>x.items_id),[2]);
await asUser(A,"select wasteless_cart('add',1,null,2)");
await asUser(A,"select wasteless_cart('add',2,null,1)");
const key='33333333-3333-4333-8333-333333333333';
const oid=(await asUser(A,'select wasteless_checkout($1) as id',[key]))[0].id;
check((await asUser(A,'select total_price::text as total from "order"'))[0].total,'9.60');
check((await asUser(A,'select * from order_items')).length,2);
check((await asUser(B,'select * from "order"')).length,0);
check((await asUser(B,'select * from order_items')).length,0);
check((await asUser(A,'select * from cart_items')).length,0);
check((await asUser(A,'select wasteless_checkout($1) as id',[key]))[0].id,oid);
check((await asUser(A,'select * from "order"')).length,1);
await denied(A,'insert into "order"(user_id,total_price) values($1,0)',[A]);
await db.exec('update product set price=99 where id=1');
check((await asUser(A,'select unit_price::text as price from order_items where product_id=1'))[0].price,'3.40');
await db.exec('update product set stock=0 where id=1');
await denied(B,'select wasteless_checkout($1)',[key]);
check((await asUser(B,'select * from "order"')).length,0);
check((await asUser(B,'select * from cart_items')).length,1);
await db.transaction(async tx=>{
 await tx.exec('set local role anon');
 await assert.rejects(tx.query('select * from cart'));checks++;
});
await db.exec('create schema tebelenoi; create table tebelenoi.cart(id bigint); grant select on tebelenoi.cart to anon,authenticated;');
await db.exec(readFileSync(new URL('../../supabase/migrations/20260928173220_wasteless_legacy_access.sql',import.meta.url),'utf8'));
check((await db.query("select relrowsecurity from pg_class where oid='tebelenoi.cart'::regclass")).rows[0].relrowsecurity,true);
check((await db.query("select has_table_privilege('anon','tebelenoi.cart','select') as permitted")).rows[0].permitted,false);

await db.exec(readFileSync(new URL('../../supabase/migrations/20260930190954_merchant_order_lifecycle.sql',import.meta.url),'utf8'));
const profile={name:'Test shop',address:'Test address 10',pickup_window:'18:00–19:00',latitude:44.435,longitude:26.102};
const mid=(await asUser(A,"select wasteless_merchant('profile',$1) as id",[profile]))[0].id;
await asUser(A,"select wasteless_merchant('seed','{}')");
await asUser(A,"select wasteless_merchant('seed','{}')");
let demo=(await asUser(A,'select * from product where merchant_id=$1 order by id',[mid]));
check(demo.length,4);
const pid=demo[0].id;
await asUser(B,"select wasteless_cart('clear')");
await asUser(B,"select wasteless_cart('add',$1,null,2)",[pid]);
const orderKey='44444444-4444-4444-8444-444444444444';
const demoOrder=(await asUser(B,'select wasteless_checkout($1) as id',[orderKey]))[0].id;
check((await asUser(A,'select stock from product where id=$1',[pid]))[0].stock,6);
check((await asUser(A,'select status from "order" where id=$1',[demoOrder]))[0].status,'confirmed');
await denied(B,"select wasteless_order_transition($1,'accepted')",[demoOrder]);
await asUser(A,"select wasteless_order_transition($1,'accepted')",[demoOrder]);
await denied(A,"select wasteless_order_transition($1,'collected','wrong')",[demoOrder]);
await asUser(A,"select wasteless_order_transition($1,'ready')",[demoOrder]);
const code=(await asUser(B,'select pickup_code from "order" where id=$1',[demoOrder]))[0].pickup_code;
await denied(A,"select wasteless_order_transition($1,'collected','wrong')",[demoOrder]);
await asUser(A,"select wasteless_order_transition($1,'collected',$2)",[demoOrder,code]);
await denied(B,"select wasteless_order_transition($1,'cancelled','','test')",[demoOrder]);
await asUser(B,"select wasteless_cart('add',$1,null,1)",[pid]);
const cancelled=(await asUser(B,'select wasteless_checkout($1) as id',['55555555-5555-4555-8555-555555555555']))[0].id;
await asUser(B,"select wasteless_order_transition($1,'cancelled','','Test cancellation')",[cancelled]);
await asUser(B,"select wasteless_order_transition($1,'cancelled','','Test cancellation')",[cancelled]);
check((await asUser(A,'select stock from product where id=$1',[pid]))[0].stock,6);
await denied(B,"select wasteless_merchant('availability',$1)",[{id:pid,active:false}]);
const values={id:pid,name:'Changed demo',price:20,original_price:50,stock:9,category:'Test',allergens:'Gluten',description:'Test',image_path:'assets/demo/rescue-bag.webp'};
await asUser(A,"select wasteless_merchant('product',$1)",[values]);
check((await asUser(B,'select price::text as price from product where id=$1',[pid]))[0].price,'20.00');
check((await asUser(B,'select unit_price::text as price from order_items where order_id=$1',[demoOrder]))[0].price,'19.00');
await denied(A,"select wasteless_merchant('product',$1)",[{...values,stock:-1}]);
const C='66666666-6666-4666-8666-666666666666';await db.query('insert into auth.users values($1)',[C]);
check((await asUser(C,'select * from "order" where id=$1',[demoOrder])).length,0);
await denied(C,"select wasteless_order_transition($1,'cancelled','','Test')",[cancelled]);
await denied(A,'update merchants set owner_id=$1 where id=$2',[B,mid]);


// Marketplace foundations: approval, shop photos, dated pickup windows.
await db.exec(readFileSync(new URL('../../supabase/migrations/20261007120000_marketplace_foundations.sql',import.meta.url),'utf8'));
check((await db.query('select status from merchants where id=$1',[mid])).rows[0].status,'approved');
check((await asUser(B,'select id from merchants where id=$1',[mid])).length,1);
const D='77777777-7777-4777-8777-777777777777', E='88888888-8888-4888-8888-888888888888';
await db.query('insert into auth.users values($1),($2)',[D,E]);
const newShop=(await asUser(D,"select wasteless_merchant('profile',$1) as id",[{...profile,name:'Cuptorul Urban'}]))[0].id;
check((await db.query('select status from merchants where id=$1',[newShop])).rows[0].status,'pending');
const bag={name:'Pachet surpriză de patiserie premium',price:22,original_price:65,stock:3,category:'Patiserie',allergens:'Poate conține: gluten',description:'Valoare estimată 65 lei',image_path:'assets/demo/rescue-bag.webp'};
const pendingBag=(await asUser(D,"select wasteless_merchant('product',$1) as id",[bag]))[0].id;
check((await asUser(D,'select id from merchants where id=$1',[newShop])).length,1);
check((await asUser(D,'select id from product where id=$1',[pendingBag])).length,1);
check((await asUser(B,'select id from merchants where id=$1',[newShop])).length,0);
check((await asUser(B,'select id from product where id=$1',[pendingBag])).length,0);
await denied(B,"select wasteless_cart('add',$1,null,1)",[pendingBag]);
await denied(B,"select wasteless_favorite($1,true)",[pendingBag]);
await denied(D,"update merchants set status='approved' where id=$1",[newShop]);
await db.query("update merchants set status='approved' where id=$1",[newShop]);
check((await asUser(B,'select id from product where id=$1',[pendingBag])).length,1);
const photo=(uid)=>`https://abc.supabase.co/storage/v1/object/public/shop-images/${uid}/shop.webp`;
await asUser(D,"select wasteless_merchant('photo',$1)",[{image_url:photo(D)}]);
check((await asUser(B,'select image_url from merchants where id=$1',[newShop]))[0].image_url,photo(D));
await denied(D,"select wasteless_merchant('photo',$1)",[{image_url:photo(E)}]);
await denied(D,"select wasteless_merchant('photo',$1)",[{image_url:'https://tracker.example/pixel.png'}]);
await asUser(D,"select wasteless_merchant('photo',$1)",[{image_url:null}]);
check((await db.query('select image_url from merchants where id=$1',[newShop])).rows[0].image_url,null);
const at=(h)=>new Date(Date.now()+h*3600e3).toISOString();
const dated=(await asUser(D,"select wasteless_merchant('product',$1) as id",[{...bag,name:'Pachet de gustări de seară',pickup_start:at(2),pickup_end:at(3)}]))[0].id;
check((await asUser(B,'select (pickup_end > pickup_start) as ok from product where id=$1',[dated]))[0].ok,true);
for (const w of [{pickup_start:at(2)},{pickup_start:at(-3),pickup_end:at(-2)},{pickup_start:at(3),pickup_end:at(2)},{pickup_start:at(200),pickup_end:at(201)},{pickup_start:at(1),pickup_end:at(14)}])
  await denied(D,"select wasteless_merchant('product',$1)",[{...bag,...w}]);
// One pickup window per order, and the order keeps the window.
await asUser(B,"select wasteless_cart('clear')");
await asUser(B,"select wasteless_cart('add',$1,null,1)",[dated]);
await asUser(B,"select wasteless_cart('add',$1,null,1)",[pendingBag]);
await denied(B,"select wasteless_checkout('99999999-9999-4999-8999-999999999991')");
await asUser(B,"select wasteless_cart('clear')");
await asUser(B,"select wasteless_cart('add',$1,null,2)",[dated]);
const datedOrder=(await asUser(B,"select wasteless_checkout('99999999-9999-4999-8999-999999999992') as id"))[0].id;
check((await asUser(B,'select (o.pickup_start = p.pickup_start and o.pickup_end = p.pickup_end) as same from "order" o, product p where o.id=$1 and p.id=$2',[datedOrder,dated]))[0].same,true);
// Expired bags disappear and cannot be bought, even from an existing cart.
await asUser(B,"select wasteless_cart('add',$1,null,1)",[dated]);
await db.query("update product set pickup_start=now()-interval '3 hours', pickup_end=now()-interval '1 hour' where id=$1",[dated]);
check((await asUser(B,'select id from product where id=$1',[dated])).length,0);
await denied(B,"select wasteless_checkout('99999999-9999-4999-8999-999999999993')");
await denied(B,"select wasteless_cart('add',$1,null,1)",[dated]);
check((await asUser(D,'select id from product where id=$1',[dated])).length,1);

console.log(`${checks} database checks passed: real SQL migration, RLS, ownership, stock, price snapshots, rollback, idempotency, approval, shop photos and pickup windows.`);
await db.close();
